### ISSUE TITLE
Question: how to use given chart version

### ISSUE THREAD

**Issue by shaunc** [loft-sh/component-chart#61]
I would like to use an emptyDir volume, which component-chart 0.8.4 supports. However, it seems that my deployments are using 0.8.2 (devspace version 5.17.0) and I can't figure out how to tell it to use a different version of the component chart.

When I add `emptyDir` I get the error:
```
[fatal]  deployments[6].helm.componentChart: component values are incorrect: yaml: unmarshal errors:
  line 49: field emptyDir not found in type latest.VolumeConfig
```
I tried removing `emptyDir` in order to deploy and then upgrade the chart, hoping I could then add back in. However, I get:
```
$ helm upgrade -n crane-web pgbouncer https://charts.devspace.sh/component-chart
Error: failed to download "https://charts.devspace.sh/component-chart"
```

**Comment by shaunc** [comment]
The workaround is, in the deployment, to have:
```yaml
deployments:
...
- name: foo
    # componentChart: true
    componentChart: false
    chart:
      repo: https://charts.devspace.sh/
      name: component-chart
      version: "0.8.4"

```
If this is the canonical way, it probably should be in the documentation.
