### ISSUE TITLE
volumes only used in initContainers are omitted from manifests

### ISSUE THREAD

**Issue by shaunc** [loft-sh/component-chart#62]
```
version: v1beta11

vars:
- name: IMAGE
  value: username/app

deployments:
- name: test
  helm:
    componentChart: true
    values:
      initContainers:
      - image: ${IMAGE}
        volumeMounts:
          - containerPath: /foo
            volume:
              name: foo
      containers:
      - image: ${IMAGE}
      volumes:
        - name: foo
          secret:
            secretName: foo        
```

yields: (`devspace render`):

```
---
# Source: component-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "test"
  labels:
    "app.kubernetes.io/name": "devspace-app"
    "app.kubernetes.io/component": "test"
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/chart": "component-chart-0.8.2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      "app.kubernetes.io/name": "devspace-app"
      "app.kubernetes.io/component": "test"
      "app.kubernetes.io/managed-by": "Helm"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "devspace-app"
        "app.kubernetes.io/component": "test"
        "app.kubernetes.io/managed-by": "Helm"
      annotations:
        "helm.sh/chart": "component-chart-0.8.2"
    spec:
      imagePullSecrets:
      nodeSelector:
        null
      nodeName:
        null
      affinity:
        null
      tolerations:
        null
      dnsConfig:
        null
      hostAliases:
        null
      overhead:
        null
      readinessGates:
        null
      securityContext:
        null
      topologySpreadConstraints:
        null
      terminationGracePeriodSeconds: 5
      ephemeralContainers:
        null
      containers:
        - image: "username/app"
          name: "container-0"
          command:
          args:
          env:
            null
          envFrom:
            null
          securityContext:
            null
          lifecycle:
            null
          livenessProbe:
            null
          readinessProbe:
            null
          startupProbe:
            null
          volumeDevices:
            null
          volumeMounts:
      initContainers:
        - image: "username/app"
          name: "init-container-0"
          command:
          args:
          env:
            null
          envFrom:
            null
          securityContext:
            null
          lifecycle:
            null
          livenessProbe:
            null
          readinessProbe:
            null
          startupProbe:
            null
          volumeDevices:
            null
          volumeMounts:
            - mountPath: "/foo"
              name: "foo"
              readOnly: false
      volumes:
  volumeClaimTemplates:
---
# Source: component-chart/templates/deployment.yaml
# Create headless service for StatefulSet
```

version: componentChart 0.8.4
devspace cli version 5.17.0
