### ISSUE TITLE
[docs] Document containers.*.envFrom

### ISSUE THREAD

**Issue by joaomlneto** [loft-sh/component-chart#75]
The documentation currently only shows how to [load single keys from Secrets and Configmaps](https://devspace.sh/component-chart/docs/configuration/containers#env) using `env.valueFrom.secretKeyRef` and `env.valueFrom.configMapKeyRef`.

However, one can use `envFrom.configMapRef` and `envFrom.secretRef` to load all variables from a ConfigMap/Secret resp.:

```
yaml
      containers:
      - image: ${IMAGE}
        envFrom:
        - configMapRef:
            name: my-config-map
```
