### ISSUE TITLE
Error when setting averageRelativeMemory in autoScaling.horizontal

### ISSUE THREAD

**Issue by Rishang** [loft-sh/component-chart#82]
For Horizontal Pod Autoscaling,

While using autoscaling based on targetAverageUtilization, in was facing this issue in DevSpace version : 6.0.1

Input:

```yaml
  replicas: 1
  autoScaling:
    horizontal:  
      maxReplicas: 3
      averageRelativeMemory: 40
```
Error:

```
ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource.targetAverageUtilization): invalid type for io.k8s.api.autoscaling.v2beta1.ResourceMetricSource.targetAverageUtilization: got "string", expected "integer"
```
