### ISSUE TITLE
[feature-request] Allow to add ConfigMaps inline

### ISSUE THREAD

**Issue by baflo** [loft-sh/component-chart#88]
For some usecases it would be great to add ConfigMaps from inline in `devspace.yaml`, so they can immediately used as volume in the containers.

It is currently possible to do this using `kustomize`'s `configMapGenerator` along with `helmChartInflationGenerator` inflating the component-chart. However, this requires an additional file and it would be great to have it all completely inline with `devspace.yaml`.

One great way to implement this, would be to directly inject files as explained here: [https://helm.sh/docs/chart_template_guide/accessing_files/#configmap-and-secrets-utility-functions](https://helm.sh/docs/chart_template_guide/accessing_files/#configmap-and-secrets-utility-functions)

**Comment by 89luca89** [comment]
Hi @baflo 

After this PR https://github.com/loft-sh/devspace/pull/2500, there is now a new feature to use `inlineManifest`, this way you can simply embed a k8s manifest yaml inside the devspace yaml, like this:

```yaml
version: v2beta1
name: inline-manifest

vars:
  IMAGE: nginx:1.14.2

deployments:
  my-deployment:
    kubectl:
      inlineManifest: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: ${IMAGE}
                ports:
                - containerPort: 80
```
